package pe.edu.upc.routeguard.core.designsystem.theme
import androidx.compose.ui.graphics.Color

// Brand palette taken from the RouteGuard landing page:
// primary #1E3A8A (navy), secondary #10B981 (emerald) and the Tailwind "slate" neutrals.
// Emerald is used as an accent; actions use the navy primary because white on #10B981 has low contrast.
val BrandNavy = Color(0xFF1E3A8A)
val BrandNavyDeep = Color(0xFF172554)
val BrandEmerald = Color(0xFF10B981)

// ---- Light ----
val primaryLight = Color(0xFF1E3A8A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDBEAFE)
val onPrimaryContainerLight = Color(0xFF172554)
val secondaryLight = Color(0xFF047857)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD1FAE5)
val onSecondaryContainerLight = Color(0xFF064E3B)
val tertiaryLight = Color(0xFF475569)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE2E8F0)
val onTertiaryContainerLight = Color(0xFF1E293B)
val errorLight = Color(0xFFB91C1C)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFEE2E2)
val onErrorContainerLight = Color(0xFF7F1D1D)
val backgroundLight = Color(0xFFF8FAFC)
val onBackgroundLight = Color(0xFF0F172A)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF0F172A)
val surfaceVariantLight = Color(0xFFE2E8F0)
val onSurfaceVariantLight = Color(0xFF475569)
val outlineLight = Color(0xFF94A3B8)
val outlineVariantLight = Color(0xFFE2E8F0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF1E293B)
val inverseOnSurfaceLight = Color(0xFFF8FAFC)
val inversePrimaryLight = Color(0xFF93C5FD)
val surfaceDimLight = Color(0xFFE2E8F0)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8FAFC)
val surfaceContainerLight = Color(0xFFF1F5F9)
val surfaceContainerHighLight = Color(0xFFE9EEF5)
val surfaceContainerHighestLight = Color(0xFFE2E8F0)

// ---- Dark (landing dark mode: slate backgrounds, blue-400 / emerald-400 accents) ----
val primaryDark = Color(0xFF60A5FA)
val onPrimaryDark = Color(0xFF0F1F4D)
val primaryContainerDark = Color(0xFF1E3A8A)
val onPrimaryContainerDark = Color(0xFFDBEAFE)
val secondaryDark = Color(0xFF34D399)
val onSecondaryDark = Color(0xFF022C22)
val secondaryContainerDark = Color(0xFF064E3B)
val onSecondaryContainerDark = Color(0xFFD1FAE5)
val tertiaryDark = Color(0xFFCBD5E1)
val onTertiaryDark = Color(0xFF1E293B)
val tertiaryContainerDark = Color(0xFF334155)
val onTertiaryContainerDark = Color(0xFFE2E8F0)
val errorDark = Color(0xFFF87171)
val onErrorDark = Color(0xFF450A0A)
val errorContainerDark = Color(0xFF7F1D1D)
val onErrorContainerDark = Color(0xFFFEE2E2)
val backgroundDark = Color(0xFF0F172A)
val onBackgroundDark = Color(0xFFE2E8F0)
val surfaceDark = Color(0xFF1E293B)
val onSurfaceDark = Color(0xFFE2E8F0)
val surfaceVariantDark = Color(0xFF334155)
val onSurfaceVariantDark = Color(0xFFCBD5E1)
val outlineDark = Color(0xFF64748B)
val outlineVariantDark = Color(0xFF334155)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E8F0)
val inverseOnSurfaceDark = Color(0xFF1E293B)
val inversePrimaryDark = Color(0xFF1E3A8A)
val surfaceDimDark = Color(0xFF0F172A)
val surfaceBrightDark = Color(0xFF334155)
val surfaceContainerLowestDark = Color(0xFF0B1220)
val surfaceContainerLowDark = Color(0xFF131D33)
val surfaceContainerDark = Color(0xFF1E293B)
val surfaceContainerHighDark = Color(0xFF263248)
val surfaceContainerHighestDark = Color(0xFF334155)
